"""empty message

Revision ID: a3f2e1a65cf1
Revises: 
Create Date: 2023-04-02 21:01:17.939042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3f2e1a65cf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.String(length=4),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###
